create table Company
(
    id           int primary key generated by default as identity,
    name         varchar(100) not null,
    email        varchar(50)  not null,
    phone_number varchar(50)  not null,
    descriptions varchar(2000),
    type         varchar(50)  not null,
    website      varchar(50),
    inn          int          not null,
    creation     timestamp default now(),
    update       timestamp default now()
)